#crear un contenedor

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: terra
      MONGO_INITDB_ROOT_PASSWORD: 425269
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
